spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huobi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
